### ISSUE TITLE
Clip augmentation consistency for pretraining

### ISSUE THREAD

**Issue by juliendenize** [martinetoering/ViCC#2]
Hi,

Thanks for sharing your work and your code.

In your pretraining code, the transformations that crop, flip, blur, and jitter have the argument `consistent = False`. However, in your paper, you mentioned that:
> Random cropping, horizontal flipping, Gaussian blur, and color jittering are used in a frame-consistent manner on RGB and flow clips following recent works [12,29].

If I understood correctly your code and launch it, the augmentations would be different for each frame in the clip, but I comprehended that the augmentations should be the same for the whole clip from your paper.

Could you provide me with some guidance on this issue, please?

Thank you

**Comment by martinetoering** [comment]
Hi @juliendenize, thank you for your interest in this work!

Yes, `consistent = False` actually still means that the augmentation is clip-wise consistent. It is consistent within the clip of `seq_len` frames. 

Only if more than one sequence is given (in one tensor), the sequences will have different augmentations each.

See also these issues:

https://github.com/TengdaHan/CoCLR/issues/3#issuecomment-717805709
https://github.com/TengdaHan/CoCLR/issues/21#issuecomment-756486396

I hope this answers your question.

**Comment by juliendenize** [comment]
Thanks for your answer, I better understand what is happening, i visualized the clips and there is still a frame-dependent augmentation, grayscale that randomly selects a channel for each frame in a sequence but I guess it shouldn't matter too much in the results.

I'll close an issue, thanks again :)
