### ISSUE TITLE
Pretrained R(2+1)D model

### ISSUE THREAD

**Issue by movingsheep** [martinetoering/ViCC#3]
Hi,
In the pretrained model part, I can only see links for pretrained S3D model. Could you also provide pretrained R(2+1)D model? Thanks.

**Comment by martinetoering** [comment]
Hi, thank you for your interest in this repo! The pretrained R(2+1)D models are now also available, links to the files can be found in the README.

**Comment by movingsheep** [comment]
Thanks for sharing the link! I will close the issue.
